# JupyterHub Helm Values - DataMeesh
proxy:
  secretToken: "9581429d57f41cad7dfcca5b4d7b11bad316edcb48317e6dc3f6845c69ff03b1"
  service:
    type: NodePort
    nodePorts:
      http: 30080

hub:
  config:
    JupyterHub:
      admin_users:
        - admin
    ConfigurableHTTPProxy:
      api_url: "http://proxy-api:8001"
    DummyAuthenticator:
      password: "datamesh2024"
    Authenticator:
      admin_users:
        - admin
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest
    pullPolicy: IfNotPresent
  cpu:
    limit: 0.5
    guarantee: 0.1
  memory:
    limit: "1G"
    guarantee: "512M"
  storage:
    capacity: "2Gi"

scheduling:
  userScheduler:
    enabled: false

cull:
  enabled: true
  timeout: 3600
  every: 600

rbac:
  create: true

debug:
  enabled: false
