# JupyterHub Helm Values - DataMeesh
proxy:
  secretToken: "d4ec6cb37f22e4ba65c2a5b9dcae5ca25661d742dd86d9e02ca013b2c1e78d24"
  service:
    type: NodePort
    nodePorts:
      http: 30080

hub:
  config:
    JupyterHub:
      admin_users:
        - admin
    DummyAuthenticator:
      password: "datamesh2024"
    Authenticator:
      admin_users:
        - admin
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest
    pullPolicy: IfNotPresent
  cpu:
    limit: 0.5
    guarantee: 0.1
  memory:
    limit: "1G"
    guarantee: "512M"
  storage:
    capacity: "2Gi"

scheduling:
  userScheduler:
    enabled: false

cull:
  enabled: true
  timeout: 3600
  every: 600

rbac:
  create: true

debug:
  enabled: false
